language: shell
os: linux
arch: amd64
dist: bionic

services: docker

branches:
  only:
    - master

env:
  - MAVEN_VERSION=3.6.3

script:
  - docker build --pull -t alvisisme/maven:$MAVEN_VERSION .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push alvisisme/maven:$MAVEN_VERSION
  - docker tag alvisisme/maven:$MAVEN_VERSION registry.cn-hangzhou.aliyuncs.com/alvisisme/maven:$MAVEN_VERSION
  - echo "$ALIYUN_PASSWORD" | docker login -u "$ALIYUN_USERNAME" --password-stdin registry.cn-hangzhou.aliyuncs.com
  - docker push registry.cn-hangzhou.aliyuncs.com/alvisisme/maven:$MAVEN_VERSION
