language: shell
os: linux
arch: amd64
dist: bionic

services: docker

branches:
  only:
    - master

env:
  - SERVER=docker.io USER=$DOCKER_USERNAME PASSWORD=$DOCKER_PASSWORD
  - SERVER=registry.cn-hangzhou.aliyuncs.com USER=$ALIYUN_USERNAME PASSWORD=$ALIYUN_PASSWORD

script:
  - docker build --pull -t $SERVER/alvisisme/maven:3.6.3 .
  - echo "$PASSWORD" | docker login -u "$USER" --password-stdin $SERVER
  - docker push $SERVER/alvisisme/maven:3.6.3
